[package]
name = "bws_plugin_interface"
version = "0.1.0"
edition = "2021"

[dependencies]
abi_stable = "0.10.4"
repr_c_types = { path = "../repr_c_types" }

[features]
default = ["plugin"]
plugin = []