[package]
name = "bws"
version = "1.0.0"
authors = ["Ponas <mykolas.peteraitis@gmail.com>"]
edition = "2018"

[dependencies]
tokio = { version = "1.4", features = ["full"] }
structopt = "0.3"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
base64 = "0.13"
futures = "0.1"
slab = "0.4.2"
hematite-nbt = "0.5.1"