[package]
name = "bws_plugin_api_derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = "1.0"
quote = "1.0"

[dev-dependencies]
bws_plugin_api = { path = "../bws_plugin_api/" }
safe_types = { path = "../safe_types/" }