[package]
name = "bws_plugin_api_derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = "1.0"
quote = "1.0"

[dev-dependencies]
bws_plugin_api = { path = "../bws_plugin_api/" }
safer-ffi = { version = "0.0.10", features = ["proc_macros"] } # TODO is this needed?