[package]
name = "bws_plugin_api"
version = "0.1.0"
edition = "2021"

[dependencies]
bws_plugin_api_derive = { path = "../bws_plugin_api_derive/", optional = true }

[features]
macro = ["bws_plugin_api_derive"]
default = ["macro"]