[package]
name = "protocol"
version = "0.1.0"
edition = "2018"

[dependencies]
protocol-derive = { path = "../protocol-derive" }
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
shrinkwraprs = "0.3.0"
bitflags = "1.2"
hematite-nbt = "0.5.1"
