[package]
name = "bws"
version = "0.4.0"
authors = ["Ponas <mykolas.peteraitis@gmail.com>"]
edition = "2021"

[dependencies]
libloading = "0.7.3"
anyhow = "1.0.53"
tokio = { version = "1.16.1", features = ["full"] }
log = "0.4.14"
env_logger = "0.9.0"
clap = { version = "3.0.14", features = ["env", "unicode", "cargo"] }
once_cell = "1.9.0"
flume = "0.10.10"
abi_stable = "0.10.4"
safe_types = { path = "../../safe_types" }
bws_plugin_interface = { path = "../bws_plugin_interface", default-features = false }
semver = "1.0.5"
petgraph = "0.6.0"
protocol = { path = "../protocol/", features = ["ser", "ffi_safe"] }