[package]
name = "bws"
version = "0.5.0"
authors = ["Ponas <mykolas.peteraitis@gmail.com>"]
edition = "2021"

[dependencies]
libloading = "0.7.3"
anyhow = "1.0.53"
tokio = { version = "1.16.1", features = ["full"] }
log = "0.4.14"
env_logger = "0.9.0"
once_cell = "1.9.0"
flume = "0.10.10"
bws_plugin_interface = { path = "../bws_plugin_interface", default-features = false }
semver = "1.0.5"
petgraph = "0.6.0"
