[package]
name = "bws"
version = "0.4.0"
authors = ["Ponas <mykolas.peteraitis@gmail.com>"]
edition = "2021"

[dependencies]
libloading = "0.7"
anyhow = "1.0"
tokio = { version = "1.15", features = ["full"]}
log = "0.4"
env_logger = "0.9"
clap = { version = "3.0", features = ["env", "unicode", "cargo"]}
once_cell = "1.9"
flume = "0.10"
abi_stable = "0.10"
repr_c_types = { git = "https://github.com/PonasKovas/repr_c_types.git" }
bws_plugin_interface = { path = "../bws_plugin_interface" }
semver = "1.0"
petgraph = "0.6"
