[package]
name = "bws"
version = "0.4.0"
authors = ["Ponas <mykolas.peteraitis@gmail.com>"]
edition = "2021"

[dependencies]
libloading = "0.7"
anyhow = "1.0.52"
tokio = { version = "1.15.0", features = ["full"]}
log = "0.4.14"
env_logger = "0.9.0"
clap = { version = "3.0", features = ["env", "unicode", "cargo"]}
once_cell = "1.9"
flume = "0.10"
abi_stable = "0.10"
bws_plugin_interface = { path = "../bws_plugin_interface" }
semver = "1.0"