[package]
name = "bws"
version = "0.5.0"
authors = ["Ponas <mykolas.peteraitis@gmail.com>"]
edition = "2021"

[dependencies]
libloading = "0.7.4"
anyhow = "1.0.68"
log = "0.4.17"
env_logger = "0.10.0"
once_cell = "1.17.0"
bws_plugin_interface = { path = "../bws_plugin_interface", default-features = false }
semver = "1.0.16"
petgraph = "0.6.2"
clap = { version = "4.0.32", features = ["env", "unicode", "string"] }